BEGIN;

DROP TABLE IF EXISTS "movie_category", "user", "movie_and_serie", "recipe_category", "recipe", "ingredient", "recipe_has_ingredient", "movie_has_category";

CREATE TABLE "movie_category" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT(now()),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" VARCHAR NOT NULL UNIQUE,
    "pseudo" VARCHAR NOT NULL UNIQUE,
    "password" VARCHAR NOT NULL,
    "avatar" VARCHAR,
    "role"  VARCHAR NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT(now()),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "movie_and_serie" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL,
    "synopsis" TEXT NOT NULL,
    "director" VARCHAR NOT NULL,
    "actor" VARCHAR NOT NULL,
    "release_date" INT NOT NULL,
    "picture" VARCHAR,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT(now()),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "recipe_category" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT(now()),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "recipe" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(125) NOT NULL,
    "description" TEXT NOT NULL,
    "picture" VARCHAR,
    "difficulty" VARCHAR NOT NULL,
    "time" VARCHAR(125) NOT NULL, 
    "instruction" TEXT NOT NULL,
    "recipe_category_id" INTEGER NOT NULL REFERENCES "recipe_category" ("id"),
    "movie_id" INTEGER NOT NULL REFERENCES "movie_and_serie" ("id"),
    "user_id" INTEGER REFERENCES "user" ("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT(now()),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "ingredient" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL,
    "picture" VARCHAR,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT(now()),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "recipe_has_ingredient" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "recipe_id" INTEGER NOT NULL REFERENCES "recipe" ("id"),
    "ingredient_id" INTEGER NOT NULL REFERENCES "ingredient" ("id"),
    "quantity" VARCHAR NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT(now()),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "movie_has_category" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "movie_and_serie_id" INTEGER NOT NULL REFERENCES "movie_and_serie" ("id"),
    "movie_category_id" INTEGER NOT NULL REFERENCES "movie_category" ("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT(now()),
    "updated_at" TIMESTAMPTZ
);

COMMIT;